name: flutter_dialpad_plus
description: A phone dialer widget that can be added to Flutter App to enable ability to dial a number. This could be combined with a voip app or with any API e.g WhatsApp API.
version: 0.2.1
# author: "Rai Ansar"
publish_to: https://pub.dev/

homepage: "https://flutterer.Dev"
repository: "https://github.com/RaiAnsar/flutter_dialpad_plus"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
